stages:
- test
- package
- deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

run-test:
  stage: test
  image: jemag/node-chrome:latest
  script:
    - npm install
    - npm run test:ci
  only:
    - branches
  except:
    - master
    - pre-production
    - production

#########################################
# Testing and packaging the application #
#########################################
run-package-dev:
  stage: package
  image: jemag/node-chrome:latest
  script:
    - npm install
    - npm run test:ci
    - npm run build:dev
  artifacts:
    paths:
      - dist
  only:
    - master

run-package-test:
  stage: package
  image: jemag/node-chrome:latest
  script:
    - npm install
    - npm run test:ci
    - npm run build:test
  artifacts:
    paths:
      - dist
  only:
    - pre-production

run-package-prod:
  stage: package
  image: jemag/node-chrome:latest
  script:
    - npm install
    - npm run test:ci
    - npm run build:prod
  artifacts:
    paths:
      - dist
  only:
    - production

##########################################################
# Deploying the application on the proper infrastructure #
##########################################################
run-deploy-dev:
    stage: deploy
    script:
      - mkdir -p /root/.ssh
      - echo "$SSH_PRIVATE_KEY_DEV" |  tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - chmod 700 /root/.ssh
      - scp -P 3031 -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r dist/* admin@132.215.33.56:/var/www/html/octo
    environment:
      name: dev
      url: http://$devHost:$devHttpPort/octo
    dependencies:
    -  run-package-dev
    only:
     - master

run-deploy-test:
    stage: deploy
    script:
      - mkdir -p /root/.ssh
      - echo "$SSH_PRIVATE_KEY_TEST" |  tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - chmod 700 /root/.ssh
      - scp -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r dist/* webogslt@srogslwebt01.uqar.ca:/var/www/html/test-www/app/octo
    environment:
      name: test
      url: http://$testHost/octo
    dependencies:
    -  run-package-test
    only:
     - pre-production

run-deploy-prod:
    stage: deploy
    script:
      - mkdir -p /root/.ssh
      - echo "$SSH_PRIVATE_KEY_PROD" |  tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - chmod 700 /root/.ssh
      - scp -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r dist/* webogsl@srogslweb01.uqar.ca:/var/www/html/www/app/octo
    environment:
      name: prod
      url: http://$prodHost/octo
    when: manual
    dependencies:
    -  run-package-prod
    only:
     - production
